#!/bin/sh
#
# insecure_httpd_wrapper - wrapper script for insecure_httpd on FreeBSD
#
# This goes in /usr/local/sbin.  It backgrounds itself, and then runs
# insecure_httpd in a loop.  If insecure_httpd exits then the script restarts
# it automatically.
#
# The -D flag tells insecure_httpd to *not* put itself into the background,
# and the -C flag tells it to get the rest of its configuration from
# the specified config file.

(
    while true ; do
	/usr/local/sbin/insecure_httpd -D -C /usr/local/www/insecure_httpd_config
	if [ -f /var/run/nologin ] ; then
	    exit
	fi
	sleep 10
	egrep ' insecure_httpd[:\[]' /var/log/messages |
	  tail -33 |
	  mail -s "insecure_httpd on `hostname` restarted" root
    done
) &
